export const femaleNames = [
	"Agune",
	"Drelil",
	"Lirann",
	"Sybil",
	"Beatrice",
	"Elgile",
	"Lirathil",
	"Theune",
	"Breagan",
	"Esme",
	"Lisabeth",
	"Wenlan",
	"Bronwyn",
	"Groua",
	"Moralil",
	"Ygwal",
	"Cannora",
	"Henaine",
	"Morgwen",
	"Yslen"
];

export const maleNames = [
	"Arwel",
	"Breglor",
	"Grinwit",
	"Melnax",
	"Bevan",
	"Canhoreal",
	"Gruwid",
	"Orthax",
	"Boroth",
	"Emrys",
	"Gruwth",
	"Triunein",
	"Borrid",
	"Ethex",
	"Gwestin",
	"Wenlan",
	"Breagle",
	"Gringle",
	"Mannog",
	"Yirmeor"
];

export const surnames = [
	"Abernathy",
	"Crumwaller",
	"Harper",
	"Swinney",
	"Addercap",
	"Dunswallow",
	"Loomer",
	"Thatcher",
	"Burl",
	"Getri",
	"Malksmilk",
	"Tolmen",
	"Candlewick",
	"Glass",
	"Smythe",
	"Weaver",
	"Cormick",
	"Harkness",
	"Sunderman",
	"Wolder"
];

export const backgrounds = [
	"Alchemist",
	"Cleric",
	"Magician",
	"Performer",
	"Blacksmith",
	"Gambler",
	"Mercenary",
	"Pickpocket",
	"Butcher",
	"Gravedigger",
	"Merchant",
	"Smuggler",
	"Burglar",
	"Herbalist",
	"Miner",
	"Servant",
	"Carpenter",
	"Hunter",
	"Outlaw",
	"Ranger"
];

export const physiques = [
	"Athletic",
	"Brawny",
	"Flabby",
	"Lanky",
	"Rugged",
	"Scrawny",
	"Short",
	"Statuesque",
	"Stout",
	"Towering"
];

export const skins = [
	"Birthmarked",
	"Marked",
	"Oily",
	"Rosy",
	"Scarred",
	"Soft",
	"Tanned",
	"Tattooed",
	"Weathered",
	"Webbed"
];

export const hairs = [
	"Bald",
	"Braided",
	"Curly",
	"Filthy",
	"Frizzy",
	"Long",
	"Luxurious",
	"Oily",
	"Wavy",
	"Wispy"
];

export const faces = [
	"Bony",
	"Broken",
	"Chiseled",
	"Elongated",
	"Pale",
	"Perfect",
	"Rakish",
	"Sharp",
	"Square",
	"Sunken"
];

export const speeches = [
	"Blunt",
	"Booming",
	"Cryptic",
	"Droning",
	"Formal",
	"Gravelly",
	"Precise",
	"Squeaky",
	"Stuttering",
	"Whispery"
];

export const clothings = [
	"Antique",
	"Bloody",
	"Elegant",
	"Filthy",
	"Foreign",
	"Frayed",
	"Frumpy",
	"Livery",
	"Rancid",
	"Soiled"
];

export const virtues = [
	"Ambitious",
	"Cautious",
	"Courageous",
	"Disciplined",
	"Gregarious",
	"Honorable",
	"Humble",
	"Merciful",
	"Serene",
	"Tolerant"
];

export const vices = [
	"Aggressive",
	"Bitter",
	"Craven",
	"Deceitful",
	"Greedy",
	"Lazy",
	"Nervous",
	"Rude",
	"Vain",
	"Vengeful"
];

export const gear = {
	armor: {
		BRIGANDINE: {
			label: "Brigandine: 1 Armor",
			armorRating: 1,
			bulky: false
		},
		CHAINMAIL: { label: "Chainamil: 2 Armor (bulky)", armorRating: 2 },
		PLATE: { label: "Plate: 3 Armor (bulky)", armorRating: 3 },
		HELMET: {
			label: "Helmet: +1 Armor",
			armorRating: 1
		},
		SHIELD: { label: "Shield: +1 Armor", armorRating: 1 }
	},
	weapons: {
		DAGGER: { label: "Dagger d6" },
		CUDGEL: { label: "Cudgel d6" },
		STAFF: { label: "Staff d6" },
		SWORD: { label: "Sword d8" },
		MACE: { label: "Mace d8" },
		AXE: { label: "Axe d8" },
		LONGBOW: { label: "Longbow d6 (bulky)" },
		CROSSBOW: { label: "Crossbow d8 (bulky)" },
		SLING: { label: "Sling d4" },
		HALBERD: { label: "Halberd d10 (bulky)" },
		WAR_HAMMER: { label: "War Hammer d10 (bulky)" },
		BATTLEAXE: { label: "Battleaxe d10 (bulky)" }
	},
	expiditionary: [
		{ label: "Air Bladder" },
		{ label: "Antitoxin" },
		{ label: "Cart (+4 slots, bulky)" },
		{ label: "Chain (10ft)" },
		{ label: "Dowsing Rod" },
		{ label: "Fire Oil" },
		{ label: "Grappling Hook" },
		{ label: "Large Sack" },
		{ label: "Large Trap" },
		{ label: "Lockpicks" },
		{ label: "Manacles" },
		{ label: "Pick" },
		{ label: "Pole (10ft)" },
		{ label: "Pulley" },
		{ label: "Repellent" },
		{ label: "Rope (25ft)" },
		{ label: "Spirit Ward" },
		{ label: "Spyglass" },
		{ label: "Tinderbox" },
		{ label: "Wolfsbane" }
	],
	tools: [
		{ label: "Bellows" },
		{ label: "Bucket" },
		{ label: "Caltrops" },
		{ label: "Chalk" },
		{ label: "Chisel" },
		{ label: "Cook Pots" },
		{ label: "Crowbar" },
		{ label: "Drill (Manual)" },
		{ label: "Fishing Rod" },
		{ label: "Glue" },
		{ label: "Grease" },
		{ label: "Hammer" },
		{ label: "Hour Glass" },
		{ label: "Metal File" },
		{ label: "Nails" },
		{ label: "Net" },
		{ label: "Saw" },
		{ label: "Sealant" },
		{ label: "Shovel" },
		{ label: "Tongs" }
	],
	trinkets: [
		{ label: "Bottle" },
		{ label: "Card Deck" },
		{ label: "Dice Set" },
		{ label: "Face Paint" },
		{ label: "Fake Jewels" },
		{ label: "Horn" },
		{ label: "Incense" },
		{ label: "Instrument" },
		{ label: "Lens" },
		{ label: "Marbles" },
		{ label: "Mirror" },
		{ label: "Perfume" },
		{ label: "Quill & Ink" },
		{ label: "Salt Pack" },
		{ label: "Small Bell" },
		{ label: "Soap" },
		{ label: "Sponge" },
		{ label: "Tar Pot" },
		{ label: "Twine" },
		{ label: "Whistle" }
	],
	spellbooks: [
		{ label: "Spellbook: Adhere" },
		{ label: "Spellbook: Anchor" },
		{ label: "Spellbook: Animate Object" },
		{ label: "Spellbook: Anthropomorphize" },
		{ label: "Spellbook: Arcane Eye" },
		{ label: "Spellbook: Astral Prison" },
		{ label: "Spellbook: Attract" },
		{ label: "Spellbook: Auditory Illusion" },
		{ label: "Spellbook: Babble" },
		{ label: "Spellbook: Bait Flower" },
		{ label: "Spellbook: Beast Form" },
		{ label: "Spellbook: Befuddle" },
		{ label: "Spellbook: Body Swap" },
		{ label: "Spellbook: Charm" },
		{ label: "Spellbook: Command" },
		{ label: "Spellbook: Comprehend" },
		{ label: "Spellbook: Cone of Foam" },
		{ label: "Spellbook: Control Plants" },
		{ label: "Spellbook: Control Weather" },
		{ label: "Spellbook: Cure Wounds" },
		{ label: "Spellbook: Deafen" },
		{ label: "Spellbook: Detect Magic" },
		{ label: "Spellbook: Disassemble" },
		{ label: "Spellbook: Disguise" },
		{ label: "Spellbook: Displace" },
		{ label: "Spellbook: Earthquake" },
		{ label: "Spellbook: Elasticity" },
		{ label: "Spellbook: Elemental Wall" },
		{ label: "Spellbook: Filch" },
		{ label: "Spellbook: Flare" },
		{ label: "Spellbook: Fog Cloud" },
		{ label: "Spellbook: Frenzy" },
		{ label: "Spellbook: Gate" },
		{ label: "Spellbook: Gravity Shift" },
		{ label: "Spellbook: Greed" },
		{ label: "Spellbook: Haste" },
		{ label: "Spellbook: Hatred" },
		{ label: "Spellbook: Hear Whispers" },
		{ label: "Spellbook: Hover" },
		{ label: "Spellbook: Hypnotize" },
		{ label: "Spellbook: Icy Touch" },
		{ label: "Spellbook: Identify Owner" },
		{ label: "Spellbook: Illuminate" },
		{ label: "Spellbook: Invisible Tether" },
		{ label: "Spellbook: Knock" },
		{ label: "Spellbook: Leap" },
		{ label: "Spellbook: Liquid Air" },
		{ label: "Spellbook: Magic Dampener" },
		{ label: "Spellbook: Manse" },
		{ label: "Spellbook: Marble Craze" },
		{ label: "Spellbook: Masquerade" },
		{ label: "Spellbook: Miniaturize" },
		{ label: "Spellbook: Mirror Image" },
		{ label: "Spellbook: Mirrorwalk" },
		{ label: "Spellbook: Multiarm" },
		{ label: "Spellbook: Night Sphere" },
		{ label: "Spellbook: Objectify" },
		{ label: "Spellbook: Ooze Form" },
		{ label: "Spellbook: Pacify" },
		{ label: "Spellbook: Phobia" },
		{ label: "Spellbook: Pit" },
		{ label: "Spellbook: Primal Surge" },
		{ label: "Spellbook: Push/Pull" },
		{ label: "Spellbook: Raise Dead" },
		{ label: "Spellbook: Raise Spirit" },
		{ label: "Spellbook: Read Mind" },
		{ label: "Spellbook: Repel" },
		{ label: "Spellbook: Scry" },
		{ label: "Spellbook: Sculpt Elements" },
		{ label: "Spellbook: Sense" },
		{ label: "Spellbook: Shield" },
		{ label: "Spellbook: Shroud" },
		{ label: "Spellbook: Shuffle" },
		{ label: "Spellbook: Sleep" },
		{ label: "Spellbook: Slick" },
		{ label: "Spellbook: Smoke Form" },
		{ label: "Spellbook: Sniff" },
		{ label: "Spellbook: Snuff" },
		{ label: "Spellbook: Sort" },
		{ label: "Spellbook: Spectacle" },
		{ label: "Spellbook: Spellsaw" },
		{ label: "Spellbook: Spider Climb" },
		{ label: "Spellbook: Summon Cube" },
		{ label: "Spellbook: Swarm" },
		{ label: "Spellbook: Telekinesis" },
		{ label: "Spellbook: Telepathy" },
		{ label: "Spellbook: Teleport" },
		{ label: "Spellbook: Target Lure" },
		{ label: "Spellbook: Thicket" },
		{ label: "Spellbook: Summon Idol" },
		{ label: "Spellbook: Time Control" },
		{ label: "Spellbook: True Sight" },
		{ label: "Spellbook: Upwell" },
		{ label: "Spellbook: Vision" },
		{ label: "Spellbook: Visual Illusion" },
		{ label: "Spellbook: Ward" },
		{ label: "Spellbook: Web" },
		{ label: "Spellbook: Widget" },
		{ label: "Spellbook: Wizard Mark" },
		{ label: "Spellbook: X-Ray Vision" }
	],
	default: [{ label: "Rations x3" }, { label: "Torch" }]
};

export const norseNames = [
	"Åsmund",
	"Æinridi",
	"Æirik",
	"Ærinmund",
	"Ærnmund",
	"Æsbiorn",
	"Æskil",
	"Ævar",
	"Øpir",
	"Øybiorn",
	"Øystæin",
	"Øysten",
	"Abi",
	"Adils",
	"Agmundr",
	"Agnar",
	"Aki",
	"Aleifr",
	"Alf",
	"Alfarin",
	"Alfgeir",
	"Alfketill",
	"Ali",
	"Alrik",
	"Alvi",
	"Amundi",
	"An",
	"Anakol",
	"Andvett",
	"Anlaf",
	"Anund",
	"Arfast",
	"Ari",
	"Arinbjorn",
	"Armod",
	"Arn",
	"Arnbjorn",
	"Arnfinn",
	"Arngeir",
	"Arngrim",
	"Arni",
	"Arnkel",
	"Arnketill",
	"Arnlaug",
	"Arnljot",
	"Arnor",
	"Arnstein",
	"Arnthor",
	"Arnulfr",
	"Arnvid",
	"Aron",
	"Asbjorn",
	"Asbrand",
	"Asfrith",
	"Asgaut",
	"Asgeir",
	"Asgrim",
	"Askel",
	"Asketill",
	"Aslak",
	"Asmund",
	"Assur",
	"Asulf",
	"Asvald",
	"Asvard",
	"Athils",
	"Atli",
	"Atsurr",
	"Auðunar",
	"Audbjorn",
	"Audgisil",
	"Audgisli",
	"Audolf",
	"Audun",
	"Austmathr",
	"Authgrim",
	"Authketill",
	"Authulf",
	"Authun",
	"Auti",
	"Balki",
	"Balli",
	"Banki",
	"Bard",
	"Bardi",
	"Baug",
	"Beigarth",
	"Beiner",
	"Beinir",
	"Berg",
	"Bergfinn",
	"Bergthor",
	"Bergvid",
	"Bersi",
	"Bior",
	"Biorn",
	"Birning",
	"Bjalfi",
	"Bjalki",
	"Bjarki",
	"Bjarni",
	"Bjartmar",
	"Bjor",
	"Bjorgolf",
	"Bjorgulf",
	"Bjorn",
	"Bjornulf",
	"Blæng",
	"Blann",
	"Bodalf",
	"Bodvar",
	"Boe",
	"Bolli",
	"Bolverk",
	"Borgar",
	"Bork",
	"Borstig",
	"Bothvar",
	"Botulf",
	"Bræsi",
	"Bragi",
	"Bram",
	"Brand",
	"Bretakollr",
	"Broddi",
	"Brodir",
	"Brondulf",
	"Bruni",
	"Brusi",
	"Bui",
	"Byrnjolf",
	"Cnut",
	"Dag",
	"Dagfinn",
	"Dan",
	"Diarf",
	"Dunfjall",
	"Dyri",
	"Edgar",
	"Egil",
	"Eid",
	"Eilif",
	"Einar",
	"Eindridi",
	"Eirik",
	"Eldgrim",
	"Elgfrothi",
	"Engli",
	"Erlend",
	"Erling",
	"Ernmund",
	"Erp",
	"Eskil",
	"Eydis",
	"Eyjolf",
	"Eystein",
	"Eyvald",
	"Eyvind",
	"Fargrim",
	"Farmann",
	"Farthegn",
	"Fastulf",
	"Finn",
	"Finnleik",
	"Finnvid",
	"Firthgest",
	"Floki",
	"Flosi",
	"Folkbiorn",
	"Folkmar",
	"Forni",
	"Frømund",
	"Freystein",
	"Fridgeir",
	"Fridmund",
	"Frodi",
	"Frostulf",
	"Frothi",
	"Gæda",
	"Gæira",
	"Gæirmund",
	"Gærhialm",
	"Gærrar",
	"Gætir",
	"Galti",
	"Gamal",
	"Gamli",
	"Gardar",
	"Gardi",
	"Gauk",
	"Gaut",
	"Gauti",
	"Gavtvid",
	"Geir",
	"Geirfinn",
	"Geirleif",
	"Geirmund",
	"Geirolf",
	"Geirstein",
	"Geirthjof",
	"Geitir",
	"Geitirgest",
	"Gellir",
	"Geri",
	"Gest",
	"Giermund",
	"Gilli",
	"Gils",
	"Gisli",
	"Gizor",
	"Gizur",
	"Glam",
	"Glum",
	"Gnupa",
	"Gnupi",
	"Gorm",
	"Grani",
	"Gretter",
	"Grettir",
	"Grim",
	"Grimar",
	"Grimkel",
	"Grimolf",
	"Grimwald",
	"Grind",
	"Griotgard",
	"Gris",
	"Grith",
	"Grjotgard",
	"Guda",
	"Gudbrand",
	"Gudlaug",
	"Gudleif",
	"Gudmund",
	"Gudrik",
	"Gudrod",
	"Gudvær",
	"Gufi",
	"Gulli",
	"Gunbjorn",
	"Gunnald",
	"Gunnar",
	"Gunnbjorn",
	"Gunnhautr",
	"Gunni",
	"Gunnkel",
	"Gunnlæif",
	"Gunnlaug",
	"Gunnleif",
	"Gunnstein",
	"Gunnulf",
	"Gunnvid",
	"Guthhere",
	"Guthorm",
	"Guthroth",
	"Guthrum",
	"Gylfi",
	"Gyrd",
	"Häming",
	"Hæfnir",
	"Hælæif",
	"Hælgi",
	"Hæming",
	"Hæng",
	"Hadd",
	"Haf",
	"Hafgrim",
	"Haflidi",
	"Hafr",
	"Hagi",
	"Haki",
	"Haklang",
	"Hakon",
	"Halfdan",
	"Halftan",
	"Hall",
	"Hallad",
	"Hallbjorn",
	"Halldor",
	"Hallfred",
	"Hallfrid",
	"Hallgrim",
	"Halli",
	"Hallkel",
	"Hallmund",
	"Hallstein",
	"Hallvard",
	"Halvdan",
	"Ham",
	"Hamund",
	"Hanef",
	"Harald",
	"Hardbein",
	"Hardrefil",
	"Harek",
	"Hastein",
	"Hauk",
	"Havard",
	"Hedin",
	"Hegg",
	"Helgi",
	"Heming",
	"Heriolf",
	"Herjolf",
	"Herlaug",
	"Herlu",
	"Hermund",
	"Herstein",
	"Hialti",
	"Hildiglum",
	"Hildir",
	"Hiorvard",
	"Hjalkar",
	"Hjalti",
	"Hjarrandi",
	"Hjor",
	"Hjorleif",
	"Hjort",
	"Hjorvarth",
	"Hlenni",
	"Hlodvir",
	"Hogni",
	"Holmfast",
	"Holmgavt",
	"Holmgeir",
	"Holmstæin",
	"Holmstein",
	"Hord",
	"Hoskuld",
	"Hosvir",
	"Hott",
	"Hrærek",
	"Hrafn",
	"Hrafnkel",
	"Hrafnvartr",
	"Hragnelf",
	"Hranfast",
	"Hrani",
	"Hrapp",
	"Hreida",
	"Hreidar",
	"Hrein",
	"Hreitharr",
	"Hrifla",
	"Hring",
	"Hroald",
	"Hroar",
	"Hrodgæir",
	"Hrodgeir",
	"Hrodi",
	"Hrok",
	"Hrolf",
	"Hrollaug",
	"Hromund",
	"Hrossbjorn",
	"Hrosskel",
	"Hrosskell",
	"Hrossketil",
	"Hrut",
	"Hunbogi",
	"Hundi",
	"Hundolfr",
	"Hvitserk",
	"Iarl",
	"Iarlabanki",
	"Iarund",
	"Illugi",
	"Ingemar",
	"Ingi",
	"Ingibjorg",
	"Ingifast",
	"Ingimar",
	"Ingimund",
	"Ingjald",
	"Ingolf",
	"Ingulbjörn",
	"Ingvar",
	"Iogæir",
	"Ioketill",
	"Iorthr",
	"Iorund",
	"Irenmund",
	"Iri",
	"Iric",
	"Isgaut",
	"Isi",
	"Isleif",
	"Isulf",
	"Iuli",
	"Ivar",
	"Jarlabanki",
	"Jarlebanke",
	"Jarnskeggi",
	"Jobjorn",
	"Johan",
	"Jokul",
	"Jomar",
	"Jon",
	"Jorund",
	"Käre",
	"Kætiløy",
	"Kætil",
	"Kætilfast",
	"Kætilmund",
	"Kabbi",
	"Kadal",
	"Kalf",
	"Kar",
	"Kari",
	"Karl",
	"Karli",
	"Karsi",
	"Kaupmann",
	"Ketil",
	"Ketilbiorn",
	"Ketilbjorn",
	"Ketill",
	"Kisping",
	"Kjallak",
	"Kjartan",
	"Kjotvi",
	"Klakkr",
	"Knútr",
	"Knut",
	"Kodran",
	"Koigrim",
	"Kol",
	"Kolbein",
	"Kolfinn",
	"Koll",
	"Kollskegg",
	"Kollsvein",
	"Kolskegg",
	"Konal",
	"Kori",
	"Kormak",
	"Kotkel",
	"Kotkell",
	"Kraki",
	"Kveldulf",
	"Lambi",
	"Leidolf",
	"Leif",
	"Leiknir",
	"Lifolf",
	"Lifstæn",
	"Lini",
	"Liut",
	"Ljot",
	"Lodin",
	"Lodmund",
	"Lopt",
	"Ludin",
	"Lyting",
	"Magnus",
	"Mak",
	"Manni",
	"Mar",
	"Meldun",
	"Modolf",
	"Moldof",
	"Mord",
	"Mursi",
	"Nærfi",
	"Naddod",
	"Nafni",
	"Nasi",
	"Nefstein",
	"Nikolas",
	"Njal",
	"Northri",
	"Odd",
	"Oddløg",
	"Oddleif",
	"Odinkar",
	"Ofeig",
	"Ofieg",
	"Ogmund",
	"Olæ",
	"Olæif",
	"Olaf",
	"Oleif",
	"Olvir",
	"Onäm",
	"Ondott",
	"Onem",
	"Ongul",
	"Onund",
	"Orøkia",
	"Orest",
	"Orgumleidi",
	"Orlyg",
	"Orm",
	"Orn",
	"Ornolf",
	"Ornulf",
	"Orri",
	"Orrin",
	"Ospak",
	"Osvald",
	"Osvif",
	"Oswald",
	"Otkel",
	"Otrygg",
	"Ottar",
	"Oystæin",
	"Ozur",
	"Paul",
	"Ragi",
	"Ragnar",
	"Ragnfast",
	"Ragnvald",
	"Raudebjorn",
	"Ref",
	"Regin",
	"Reinn",
	"Rodmar",
	"Rognvald",
	"Runolf",
	"Sæbbi",
	"Sæmund",
	"Sævil",
	"Saksi",
	"Sam",
	"Saxi",
	"Selkollr",
	"Serk",
	"Sibbi",
	"Sigbjorn",
	"Sigbrand",
	"Sigebeorht",
	"Sigeferth",
	"Sigegar",
	"Sigeheah",
	"Sigehelm",
	"Sigehere",
	"Sigelac",
	"Sigemær",
	"Sigemund",
	"Sigenoth",
	"Sigeræd",
	"Sigeric",
	"Sigestæl",
	"Sigeweard",
	"Sigewine",
	"Sigewulf",
	"Sigfast",
	"Sigfus",
	"Sigguatr",
	"Sighadd",
	"Sighvat",
	"Sigmund",
	"Sigtrygg",
	"Sigurd",
	"Sigvaldi",
	"Sigvat",
	"Sigvid",
	"Sinfiotli",
	"Singasven",
	"Skœdir",
	"Skallagrim",
	"Skamkel",
	"Skap",
	"Skapti",
	"Skard",
	"Skardi",
	"Skarf",
	"Skegg",
	"Skeggi",
	"Skialg",
	"Skidi",
	"Skjaldulf",
	"Skjold",
	"Skopti",
	"Skorri",
	"Skuf",
	"Skuld",
	"Skuli",
	"Skurfa",
	"Skuti",
	"Slode",
	"Slodi",
	"Slothi",
	"Snæbjorn",
	"Snækol",
	"Snorri",
	"Sod",
	"Sokkolf",
	"Solmund",
	"Solvi",
	"Sorli",
	"Spiallbudi",
	"Spiut",
	"Spjut",
	"Stækar",
	"Starkad",
	"Starolf",
	"Starri",
	"Stein",
	"Steinar",
	"Steinbitr",
	"Steinbjorn",
	"Steingrim",
	"Steinkel",
	"Steinketill",
	"Steinmod",
	"Steinolf",
	"Steinthor",
	"Steinunn",
	"Stigandi",
	"Storolf",
	"Stuf",
	"Sturla",
	"Styr",
	"Styrbiorn",
	"Styrkar",
	"Styrkollr",
	"Styrmir",
	"Suit",
	"Sumarlid",
	"Sumarlidi",
	"Surt",
	"Svæin",
	"Svafar",
	"Svalfi",
	"Svan",
	"Svart",
	"Svartbrand",
	"Svartgeirr",
	"Svartkollr",
	"Svartlingr",
	"Svein",
	"Sveinbjorn",
	"Sven",
	"Sveni",
	"Sverting",
	"Svinulf",
	"Svipday",
	"Swein",
	"Teit",
	"Thangbrand",
	"Thialfi",
	"Thidrandi",
	"Thidrik",
	"Thiodolf",
	"Thjodofl",
	"Thjodoft",
	"Thjostolf",
	"Thokodolf",
	"Thometill",
	"Thorald",
	"Thoraldr",
	"Thorarin",
	"Thorberg",
	"Thorbjorn",
	"Thorbrand",
	"Thord",
	"Thorfast",
	"Thorfinn",
	"Thorfrethr",
	"Thorgaut",
	"Thorgeir",
	"Thorgest",
	"Thorgils",
	"Thorgrim",
	"Thorhall",
	"Thorir",
	"Thorkel",
	"Thorkell",
	"Thorketil",
	"Thorlak",
	"Thorleif",
	"Thorleik",
	"Thormar",
	"Thormod",
	"Thormothr",
	"Thoroard",
	"Thorod",
	"Thorodd",
	"Thorolf",
	"Thororm",
	"Thorred",
	"Thorstar",
	"Thorstein",
	"Thorvald",
	"Thorvard",
	"Thorvid",
	"Thrain",
	"Thrand",
	"Throst",
	"Tjorvi",
	"Tofi",
	"Toki",
	"Tola",
	"Tore",
	"Torfi",
	"Torrad",
	"Torsten",
	"Tosti",
	"Trandil",
	"Trud",
	"Trygg",
	"Tryggvi",
	"Tufi",
	"Tumi",
	"Tyrfing",
	"Tyrkir",
	"Ubbein",
	"Ufi",
	"Uglubathr",
	"Ulf",
	"Ulfar",
	"Ulfbjorn",
	"Ulfgrim",
	"Ulfketil",
	"Ulfljot",
	"Ulfrik",
	"Ulvkil",
	"Uni",
	"Unn",
	"Unnulf",
	"Värmod",
	"Valbrand",
	"Valgard",
	"Vali",
	"Valthjof",
	"Vandil",
	"Vandrad",
	"Var",
	"Varin",
	"Vathlauss",
	"Vebjorn",
	"Vebrand",
	"Vegeir",
	"Vekel",
	"Veleif",
	"Vermund",
	"Vertlithi",
	"Vestar",
	"Vestein",
	"Vestgeir",
	"Veturlidi",
	"Vidkunn",
	"Vifil",
	"Vigbjord",
	"Vigfus",
	"Vigi",
	"Vigot",
	"Vikar",
	"Visäte",
	"Vog",
	"Vott",
	"Waltheof",
	"Wary",
	"Wealglist",
	"Wengo",
	"Yngvar",
	"Ysoppa",

	"Æsa",
	"Æstrid",
	"Þuriðr",
	"Abi",
	"Aldis",
	"Alfdis",
	"Alfeid",
	"Alof",
	"Armod",
	"Arnbjorg",
	"Arngunn",
	"Arnkatla",
	"Arnora",
	"Arnthrud",
	"Asa",
	"Asdis",
	"Asfrid",
	"Asgard",
	"Asgerd",
	"Ashild",
	"Aslaug",
	"Asleif",
	"Asny",
	"Asta",
	"Astrid",
	"Asvor",
	"Aud",
	"Audbjorg",
	"Audhild",
	"Bera",
	"Bergljot",
	"Bergthora",
	"Bjartney",
	"Bjorg",
	"Bolla",
	"Bothild",
	"Brynhild",
	"Dalla",
	"Dotta",
	"Drifa",
	"Droplaug",
	"Ermingard",
	"Estrid",
	"Fastvi",
	"Freydis",
	"Freygerd",
	"Frida",
	"Frideburg",
	"Fridgerd",
	"Gæierlaug",
	"Geirhild",
	"Geirlaug",
	"Geirny",
	"Gerd",
	"Gerrid",
	"Gillaug",
	"Ginnlaug",
	"Gjaflaug",
	"Greiland",
	"Grelod",
	"Grima",
	"Grimhild",
	"Gro",
	"Groa",
	"Guðný",
	"Gudbjorg",
	"Gudfinna",
	"Gudfrid",
	"Gudlang",
	"Gudney",
	"Gudny",
	"Gudrid",
	"Gudrun",
	"Gunnhild",
	"Gunnvor",
	"Gyda",
	"Gyrd",
	"Gyrid",
	"Halla",
	"Hallbera",
	"Hallberta",
	"Halldis",
	"Halldora",
	"Hallfrid",
	"Hallgerd",
	"Hallgrim",
	"Hallkatla",
	"Hallveig",
	"Hedinfrid",
	"Heith",
	"Helga",
	"Herbjorg",
	"Herdis",
	"Herkja",
	"Hervor",
	"Hild",
	"Hilde",
	"Hildigunn",
	"Hildirid",
	"Hlif",
	"Holmfrid",
	"Holmlaug",
	"Hrafnhild",
	"Hrefna",
	"Hrodny",
	"Hungerd",
	"Inga",
	"Ingegärd",
	"Ingeltore",
	"Ingibjorg",
	"Ingigerd",
	"Ingirid",
	"Ingirun",
	"Ingithora",
	"Ingrid",
	"Ingulfrid",
	"Ingun",
	"Ingunn",
	"Isgerd",
	"Jaddvor",
	"Jarngerd",
	"Jodis",
	"Jofrid",
	"Joreid",
	"Jorunn",
	"Kadlin",
	"Katla",
	"Ketiloy",
	"Ljot",
	"Ljufa",
	"Ljufu",
	"Luta",
	"Mœid",
	"Maria",
	"Matilda",
	"Melkorka",
	"Nidbiorg",
	"Nidbjorg",
	"Oddbjorg",
	"Oddny",
	"Odindis",
	"Ogn",
	"Olof",
	"Ormhild",
	"Osk",
	"Ottkatla",
	"Rafarta",
	"Raghild",
	"Ragna",
	"Ragneid",
	"Ragnfrid",
	"Ragnhild",
	"Rannveig",
	"Ranveig",
	"Reginleif",
	"Runa",
	"Sæunn",
	"Salbjorg",
	"Sibbe",
	"Signy",
	"Sigrid",
	"Sigrunn",
	"Sigvor",
	"Siv",
	"Skuld",
	"Skur",
	"Solveig",
	"Solvor",
	"Steinunn",
	"Steinvor",
	"Styrlaug",
	"Svala",
	"Svanhild",
	"Svanlaug",
	"Thjodhild",
	"Thkatla",
	"Thora",
	"Thorballa",
	"Thorbjorg",
	"Thordis",
	"Thorelf",
	"Thorfinna",
	"Thorfrid",
	"Thorfrithr",
	"Thorgærd",
	"Thorgerd",
	"Thorgrima",
	"Thorgunna",
	"Thorhalla",
	"Thorhild",
	"Thorkatla",
	"Thorlaug",
	"Thorljot",
	"Thorunn",
	"Thorve",
	"Thorvor",
	"Thraslaug",
	"Thurid",
	"Thyre",
	"Thyri",
	"Tofa",
	"Tola",
	"Tonna",
	"Torgärd",
	"Torhild",
	"Torunn",
	"Turid",
	"Ulfeid",
	"Ulfheid",
	"Una",
	"Unn",
	"Valborg",
	"Valgerd",
	"Vandrad",
	"Vigdis",
	"Yngvild",
	"Yri",
	"Yrsa"
];

export const clanValues = [
	// openness to new things
	{ YES: "open to newcomers", NO: "wary of newcomers" },
	{ YES: "open to galdr magic", NO: "wary of galdr magic" },
	{ YES: "open to seiðr magic", NO: "wary of seiðr magic" },
	{ YES: "open to The Light", NO: "wary of The Light" },

	// resources
	{
		YES: "well-off due to dwarven creations",
		NO: "worse-off due to dwarven creations"
	},
	{ YES: "self-sufficient", NO: "dependent on trade/help" },
	{ YES: "wealthy", NO: "poor" },

	// religion
	{ YES: "devoted to the old gods", NO: "opposed to the old gods" },
	{ YES: "engaged in horrific rituals" },
	{ YES: "secretive about religious practices" },
	{
		YES: "tolerant of witchcraft/demon worship",
		NO: "intolerant of witchcraft/demon worship"
	},

	// relationships with others
	{ YES: "diplomatic negotiators", NO: "violent negotiators" },
	{ YES: "in harmony with nature", NO: "in conflict with nature" },
	{ YES: "in harmony with other clans", NO: "in conflict with other clans" },
	{ YES: "in harmony with non-humans", NO: "in conflict with non-humans" },

	// values & conduct
	{
		YES: "dogmatic about social norms & taboos",
		NO: "permissive about social norms & taboos"
	},
	{ YES: "charitable, even to outsiders", NO: "corrupt & exploitative" },
	{ YES: "bloodthirsty when resolving legal matters", NO: "" },
	{
		YES: "fond of drunkeness to bond and mark occasions",
		NO: "disapproving of drunkeness"
	},
	{ YES: "dutifully hospitable", NO: "private & unwelcoming" },
	{
		YES: "opportunistic & self-serving",
		NO: "conformist & expect obedience"
	},
	{ YES: "strictly honour-bound", NO: "cynical & suspicious" },
	{ YES: "reverent of war for honour", NO: "cynical & practical about war" }
];

export const storeInventory = [
	{ label: "Air Bladder", price: 20, faulty: false, count: 1 },
	{ label: "Bedroll", price: 10, faulty: false, count: 1 },
	{ label: "Bellows", price: 15, faulty: false, count: 1 },
	{ label: "Book", price: 90, faulty: false, count: 1 },
	{ label: "Bucket", price: 5, faulty: false, count: 1 },
	{ label: "Caltrops", price: 20, faulty: false, count: 1 },
	{ label: "Cart (+4 slots, bulky)", price: 70, faulty: false, count: 1 },
	{ label: "Chain(10ft)", price: 20, faulty: false, count: 1 },
	{ label: "Chalk", price: 2, faulty: false, count: 1 },
	{ label: "Chisel", price: 15, faulty: false, count: 1 },
	{ label: "Cooking Pots", price: 10, faulty: false, count: 1 },
	{ label: "Crowbar", price: 15, faulty: false, count: 1 },
	{ label: "Drill (Manual)", price: 15, faulty: false, count: 1 },
	{ label: "Face Paint", price: 10, faulty: false, count: 1 },
	{ label: "Fishing Rod", price: 10, faulty: false, count: 1 },
	{ label: "Glue", price: 10, faulty: false, count: 1 },
	{ label: "Grappling Hook", price: 20, faulty: false, count: 1 },
	{ label: "Grease", price: 10, faulty: false, count: 1 },
	{ label: "Hammer", price: 15, faulty: false, count: 1 },
	{ label: "Holy Water", price: 90, faulty: false, count: 1 },
	{ label: "Horn", price: 10, faulty: false, count: 1 },
	{ label: "Horse(+4 slots)", price: 75, faulty: false, count: 1 },
	{ label: "Hourglass", price: 100, faulty: false, count: 1 },
	{ label: "Incense", price: 10, faulty: false, count: 1 },
	{ label: "Ladder (bulky, 10ft)", price: 10, faulty: false, count: 1 },
	{ label: "Lantern & Oil", price: 15, faulty: false, count: 1 },
	{ label: "Large Sponge", price: 5, faulty: false, count: 1 },
	{ label: "Large Trap", price: 50, faulty: false, count: 1 },
	{ label: "Lens", price: 80, faulty: false, count: 1 },
	{ label: "Lockpicks", price: 30, faulty: false, count: 1 },
	{ label: "Manacles", price: 20, faulty: false, count: 1 },
	{ label: "Marbles", price: 10, faulty: false, count: 1 },
	{ label: "Metal File", price: 15, faulty: false, count: 1 },
	{ label: "Mirror", price: 15, faulty: false, count: 1 },
	{ label: "Mule(+6 slots, slow)", price: 40, faulty: false, count: 1 },
	{ label: "Net", price: 15, faulty: false, count: 1 },
	{ label: "Oilskin Bag", price: 15, faulty: false, count: 1 },
	{ label: "Pick", price: 15, faulty: false, count: 1 },
	{ label: "Pole (10ft)", price: 10, faulty: false, count: 1 },
	{ label: "Pulley", price: 15, faulty: false, count: 1 },
	{ label: "Quill & Ink", price: 20, faulty: false, count: 1 },
	{ label: "Rations (three days’ worth)", price: 5, faulty: false, count: 1 },
	{ label: "Rope (25ft)", price: 10, faulty: false, count: 1 },
	{ label: "Sack", price: 5, faulty: false, count: 1 },
	{ label: "Saw", price: 15, faulty: false, count: 1 },
	{ label: "Shovel", price: 15, faulty: false, count: 1 },
	{ label: "Skis", price: 50, faulty: false, count: 1 },
	{ label: "Soap", price: 5, faulty: false, count: 1 },
	{ label: "Spike", price: 10, faulty: false, count: 1 },
	{ label: "Spiked Boots", price: 55, faulty: false, count: 1 },
	{ label: "Spyglass", price: 120, faulty: false, count: 1 },
	{ label: "Tar", price: 10, faulty: false, count: 1 },
	{
		label: "Tent (fits 2 people, bulky)",
		price: 15,
		faulty: false,
		count: 1
	},
	{ label: "Torch", price: 2, faulty: false, count: 1 },
	{ label: "Wagon (+8 slots, slow)", price: 100, faulty: false, count: 1 },
	{ label: "Wolfsbane", price: 10, faulty: false, count: 1 },
	{ label: "Dagger", price: 20, faulty: false, count: 1 },
	{ label: "Sickle", price: 20, faulty: false, count: 1 },
	{ label: "Cudgel", price: 10, faulty: false, count: 1 },
	{ label: "Staff", price: 10, faulty: false, count: 1 },
	{ label: "Axe", price: 50, faulty: false, count: 1 },
	{ label: "Spear", price: 50, faulty: false, count: 1 },
	{ label: "Mace", price: 50, faulty: false, count: 1 },
	{ label: "Sword", price: 150, faulty: false, count: 1 },
	{ label: "Dane Axe", price: 80, faulty: false, count: 1 },
	{ label: "Greatsword", price: 300, faulty: false, count: 1 },
	{ label: "Sling", price: 10, faulty: false, count: 1 },
	{ label: "Bow", price: 70, faulty: false, count: 1 },
	{ label: "Crossbow", price: 100, faulty: false, count: 1 },
	{ label: "Shield", price: 50, faulty: false, count: 1 },
	{ label: "Gambeson", price: 50, faulty: false, count: 1 },
	{ label: "Helmet", price: 80, faulty: false, count: 1 },
	{ label: "Lamellar", price: 100, faulty: false, count: 1 },
	{ label: "Chainmail", price: 300, faulty: false, count: 1 },
	{ label: "Plate", price: 1200, faulty: false, count: 1 }
];
