export const femaleNames = [
	"Agune",
	"Drelil",
	"Lirann",
	"Sybil",
	"Beatrice",
	"Elgile",
	"Lirathil",
	"Theune",
	"Breagan",
	"Esme",
	"Lisabeth",
	"Wenlan",
	"Bronwyn",
	"Groua",
	"Moralil",
	"Ygwal",
	"Cannora",
	"Henaine",
	"Morgwen",
	"Yslen"
];

export const maleNames = [
	"Arwel",
	"Breglor",
	"Grinwit",
	"Melnax",
	"Bevan",
	"Canhoreal",
	"Gruwid",
	"Orthax",
	"Boroth",
	"Emrys",
	"Gruwth",
	"Triunein",
	"Borrid",
	"Ethex",
	"Gwestin",
	"Wenlan",
	"Breagle",
	"Gringle",
	"Mannog",
	"Yirmeor"
];

export const surnames = [
	"Abernathy",
	"Crumwaller",
	"Harper",
	"Swinney",
	"Addercap",
	"Dunswallow",
	"Loomer",
	"Thatcher",
	"Burl",
	"Getri",
	"Malksmilk",
	"Tolmen",
	"Candlewick",
	"Glass",
	"Smythe",
	"Weaver",
	"Cormick",
	"Harkness",
	"Sunderman",
	"Wolder"
];

export const backgrounds = [
	"Alchemist",
	"Cleric",
	"Magician",
	"Performer",
	"Blacksmith",
	"Gambler",
	"Mercenary",
	"Pickpocket",
	"Butcher",
	"Gravedigger",
	"Merchant",
	"Smuggler",
	"Burglar",
	"Herbalist",
	"Miner",
	"Servant",
	"Carpenter",
	"Hunter",
	"Outlaw",
	"Ranger"
];

export const physiques = [
	"Athletic",
	"Brawny",
	"Flabby",
	"Lanky",
	"Rugged",
	"Scrawny",
	"Short",
	"Statuesque",
	"Stout",
	"Towering"
];

export const skins = [
	"Birthmarked",
	"Marked",
	"Oily",
	"Rosy",
	"Scarred",
	"Soft",
	"Tanned",
	"Tattooed",
	"Weathered",
	"Webbed"
];

export const hairs = [
	"Bald",
	"Braided",
	"Curly",
	"Filthy",
	"Frizzy",
	"Long",
	"Luxurious",
	"Oily",
	"Wavy",
	"Wispy"
];

export const faces = [
	"Bony",
	"Broken",
	"Chiseled",
	"Elongated",
	"Pale",
	"Perfect",
	"Rakish",
	"Sharp",
	"Square",
	"Sunken"
];

export const speeches = [
	"Blunt",
	"Booming",
	"Cryptic",
	"Droning",
	"Formal",
	"Gravelly",
	"Precise",
	"Squeaky",
	"Stuttering",
	"Whispery"
];

export const clothings = [
	"Antique",
	"Bloody",
	"Elegant",
	"Filthy",
	"Foreign",
	"Frayed",
	"Frumpy",
	"Livery",
	"Rancid",
	"Soiled"
];

export const virtues = [
	"Ambitious",
	"Cautious",
	"Courageous",
	"Disciplined",
	"Gregarious",
	"Honorable",
	"Humble",
	"Merciful",
	"Serene",
	"Tolerant"
];

export const vices = [
	"Aggressive",
	"Bitter",
	"Craven",
	"Deceitful",
	"Greedy",
	"Lazy",
	"Nervous",
	"Rude",
	"Vain",
	"Vengeful"
];

export const gear = {
	armor: {
		BRIGANDINE: {
			label: "Brigandine: 1 Armor",
			armorRating: 1,
			bulky: false
		},
		CHAINMAIL: { label: "Chainamil: 2 Armor (bulky)", armorRating: 2 },
		PLATE: { label: "Plate: 3 Armor (bulky)", armorRating: 3 },
		HELMET: {
			label: "Helmet: +1 Armor",
			armorRating: 1
		},
		SHIELD: { label: "Shield: +1 Armor", armorRating: 1 }
	},
	weapons: {
		DAGGER: { label: "Dagger d6" },
		CUDGEL: { label: "Cudgel d6" },
		STAFF: { label: "Staff d6" },
		SWORD: { label: "Sword d8" },
		MACE: { label: "Mace d8" },
		AXE: { label: "Axe d8" },
		LONGBOW: { label: "Longbow d6 (bulky)" },
		CROSSBOW: { label: "Crossbow d8 (bulky)" },
		SLING: { label: "Sling d4" },
		HALBERD: { label: "Halberd d10 (bulky)" },
		WAR_HAMMER: { label: "War Hammer d10 (bulky)" },
		BATTLEAXE: { label: "Battleaxe d10 (bulky)" }
	},
	expiditionary: [
		{ label: "Air Bladder" },
		{ label: "Antitoxin" },
		{ label: "Cart (+4 slots, bulky)" },
		{ label: "Chain (10ft)" },
		{ label: "Dowsing Rod" },
		{ label: "Fire Oil" },
		{ label: "Grappling Hook" },
		{ label: "Large Sack" },
		{ label: "Large Trap" },
		{ label: "Lockpicks" },
		{ label: "Manacles" },
		{ label: "Pick" },
		{ label: "Pole (10ft)" },
		{ label: "Pulley" },
		{ label: "Repellent" },
		{ label: "Rope (25ft)" },
		{ label: "Spirit Ward" },
		{ label: "Spyglass" },
		{ label: "Tinderbox" },
		{ label: "Wolfsbane" }
	],
	tools: [
		{ label: "Bellows" },
		{ label: "Bucket" },
		{ label: "Caltrops" },
		{ label: "Chalk" },
		{ label: "Chisel" },
		{ label: "Cook Pots" },
		{ label: "Crowbar" },
		{ label: "Drill (Manual)" },
		{ label: "Fishing Rod" },
		{ label: "Glue" },
		{ label: "Grease" },
		{ label: "Hammer" },
		{ label: "Hour Glass" },
		{ label: "Metal File" },
		{ label: "Nails" },
		{ label: "Net" },
		{ label: "Saw" },
		{ label: "Sealant" },
		{ label: "Shovel" },
		{ label: "Tongs" }
	],
	trinkets: [
		{ label: "Bottle" },
		{ label: "Card Deck" },
		{ label: "Dice Set" },
		{ label: "Face Paint" },
		{ label: "Fake Jewels" },
		{ label: "Horn" },
		{ label: "Incense" },
		{ label: "Instrument" },
		{ label: "Lens" },
		{ label: "Marbles" },
		{ label: "Mirror" },
		{ label: "Perfume" },
		{ label: "Quill & Ink" },
		{ label: "Salt Pack" },
		{ label: "Small Bell" },
		{ label: "Soap" },
		{ label: "Sponge" },
		{ label: "Tar Pot" },
		{ label: "Twine" },
		{ label: "Whistle" }
	],
	spellbooks: [
		{ label: "Spellbook:Adhere" },
		{ label: "Spellbook:Anchor" },
		{ label: "Spellbook:Animate Object" },
		{ label: "Spellbook:Anthropomorphize" },
		{ label: "Spellbook:Arcane Eye" },
		{ label: "Spellbook:Astral Prison" },
		{ label: "Spellbook:Attract" },
		{ label: "Spellbook:Auditory Illusion" },
		{ label: "Spellbook:Babble" },
		{ label: "Spellbook:Bait Flower" },
		{ label: "Spellbook:Beast Form" },
		{ label: "Spellbook:Befuddle" },
		{ label: "Spellbook:Body Swap" },
		{ label: "Spellbook:Charm" },
		{ label: "Spellbook:Command" },
		{ label: "Spellbook:Comprehend" },
		{ label: "Spellbook:Cone of Foam" },
		{ label: "Spellbook:Control Plants" },
		{ label: "Spellbook:Control Weather" },
		{ label: "Spellbook:Cure Wounds" },
		{ label: "Spellbook:Deafen" },
		{ label: "Spellbook:Detect Magic" },
		{ label: "Spellbook:Disassemble" },
		{ label: "Spellbook:Disguise" },
		{ label: "Spellbook:Displace" },
		{ label: "Spellbook:Earthquake" },
		{ label: "Spellbook:Elasticity" },
		{ label: "Spellbook:Elemental Wall" },
		{ label: "Spellbook:Filch" },
		{ label: "Spellbook:Flare" },
		{ label: "Spellbook:Fog Cloud" },
		{ label: "Spellbook:Frenzy" },
		{ label: "Spellbook:Gate" },
		{ label: "Spellbook:Gravity Shift" },
		{ label: "Spellbook:Greed" },
		{ label: "Spellbook:Haste" },
		{ label: "Spellbook:Hatred" },
		{ label: "Spellbook:Hear Whispers" },
		{ label: "Spellbook:Hover" },
		{ label: "Spellbook:Hypnotize" },
		{ label: "Spellbook:Icy Touch" },
		{ label: "Spellbook:Identify Owner" },
		{ label: "Spellbook:Illuminate" },
		{ label: "Spellbook:Invisible Tether" },
		{ label: "Spellbook:Knock" },
		{ label: "Spellbook:Leap" },
		{ label: "Spellbook:Liquid Air" },
		{ label: "Spellbook:Magic Dampener" },
		{ label: "Spellbook:Manse" },
		{ label: "Spellbook:Marble Craze" },
		{ label: "Spellbook:Masquerade" },
		{ label: "Spellbook:Miniaturize" },
		{ label: "Spellbook:Mirror Image" },
		{ label: "Spellbook:Mirrorwalk" },
		{ label: "Spellbook:Multiarm" },
		{ label: "Spellbook:Night Sphere" },
		{ label: "Spellbook:Objectify" },
		{ label: "Spellbook:Ooze Form" },
		{ label: "Spellbook:Pacify" },
		{ label: "Spellbook:Phobia" },
		{ label: "Spellbook:Pit" },
		{ label: "Spellbook:Primal Surge" },
		{ label: "Spellbook:Push/Pull" },
		{ label: "Spellbook:Raise Dead" },
		{ label: "Spellbook:Raise Spirit" },
		{ label: "Spellbook:Read Mind" },
		{ label: "Spellbook:Repel" },
		{ label: "Spellbook:Scry" },
		{ label: "Spellbook:Sculpt Elements" },
		{ label: "Spellbook:Sense" },
		{ label: "Spellbook:Shield" },
		{ label: "Spellbook:Shroud" },
		{ label: "Spellbook:Shuffle" },
		{ label: "Spellbook:Sleep" },
		{ label: "Spellbook:Slick" },
		{ label: "Spellbook:Smoke Form" },
		{ label: "Spellbook:Sniff" },
		{ label: "Spellbook:Snuff" },
		{ label: "Spellbook:Sort" },
		{ label: "Spellbook:Spectacle" },
		{ label: "Spellbook:Spellsaw" },
		{ label: "Spellbook:Spider Climb" },
		{ label: "Spellbook:Summon Cube" },
		{ label: "Spellbook:Swarm" },
		{ label: "Spellbook:Telekinesis" },
		{ label: "Spellbook:Telepathy" },
		{ label: "Spellbook:Teleport" },
		{ label: "Spellbook:Target Lure" },
		{ label: "Spellbook:Thicket" },
		{ label: "Spellbook:Summon Idol" },
		{ label: "Spellbook:Time Control" },
		{ label: "Spellbook:True Sight" },
		{ label: "Spellbook:Upwell" },
		{ label: "Spellbook:Vision" },
		{ label: "Spellbook:Visual Illusion" },
		{ label: "Spellbook:Ward" },
		{ label: "Spellbook:Web" },
		{ label: "Spellbook:Widget" },
		{ label: "Spellbook:Wizard Mark" },
		{ label: "Spellbook:X-Ray Vision" }
	],
	default: [{ label: "Rations x3" }, { label: "Torch" }]
};
